### ISSUE TITLE
New Feature - support pass arguments to command 

### ISSUE THREAD

**Issue by owenchenxy** [owenchenxy/rusthook#1]
like the configuration in `hooks.hexample.config`:
```
  pass_arguments_to_command: 
  - source: payload
    name: user.id
  - source: string
    name: "args"
```

support referencing request values as the parameters for the execute_command.
